-- MySQL Script generated by MySQL Workbench
-- Sun Feb 27 19:22:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `IdPersona` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(250) NOT NULL,
  `Genero` VARCHAR(50) NOT NULL,
  `Edad` INT NOT NULL,
  `Identificacion` VARCHAR(15) NOT NULL,
  `Direccion` VARCHAR(250) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `Contraseña` VARCHAR(250) NOT NULL,
  `Estado` TINYINT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`IdCliente`),
  INDEX `fk_Cliente_Persona_idx` (`Persona_IdPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Persona`
    FOREIGN KEY (`Persona_IdPersona`)
    REFERENCES `mydb`.`Persona` (`IdPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cuenta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cuenta` (
  `IdCuenta` INT NOT NULL AUTO_INCREMENT,
  `NumeroCuenta` INT NOT NULL,
  `TipoCuenta` VARCHAR(45) NOT NULL,
  `SaldoInicial` DOUBLE NOT NULL,
  `Estado` TINYINT NOT NULL,
  `Cliente_IdCliente` INT NOT NULL,
  PRIMARY KEY (`IdCuenta`),
  INDEX `fk_Cuenta_Cliente1_idx` (`Cliente_IdCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cuenta_Cliente1`
    FOREIGN KEY (`Cliente_IdCliente`)
    REFERENCES `mydb`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Movimientos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Movimientos` (
  `IdMovimientos` INT NOT NULL AUTO_INCREMENT,
  `FechaMovimiento` DATE NOT NULL,
  `TipoMovimiento` VARCHAR(45) NOT NULL,
  `Valor` DOUBLE NOT NULL,
  `Saldo` DOUBLE NOT NULL,
  `Cuenta_idCuenta` INT NOT NULL,
  PRIMARY KEY (`IdMovimientos`),
  INDEX `fk_Movimientos_Cuenta1_idx` (`Cuenta_IdCuenta` ASC) VISIBLE,
  CONSTRAINT `fk_Movimientos_Cuenta1`
    FOREIGN KEY (`Cuenta_IdCuenta`)
    REFERENCES `mydb`.`Cuenta` (`IdCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
